const SET_PIE_CHART = 'SET_PIE_CHART';
const SET_DATE_PIE_CHART = 'SET_DATE_PIE_CHART';
const SET_PIE_CHART_LOADING = 'SET_PIE_CHART_LOADING';
const SET_PIE_CHART_ERROR = 'SET_PIE_CHART_ERROR';
const SET_CHART_TYPE_PIE = 'SET_CHART_TYPE_PIE';
const SET_LINE_CHART = 'SET_LINE_CHART';
const SET_LINE_CHART_LOADING = 'SET_LINE_CHART_LOADING';
const SET_LINE_CHART_ERROR = 'SET_LINE_CHART_ERROR';
const SET_JOBS = 'SET_JOBS';
const SET_JOBS_LOADING = 'SET_JOBS_LOADING';
const SET_JOBS_ERROR = 'SET_JOBS_ERROR';
const SET_DATE = 'SET_DATE';
const SET_LINE_LANGUAGES = 'SET_LINE_LANGUAGES';
const SET_SEARCH = 'SET_SEARCH';

export default {
  SET_PIE_CHART,
  SET_DATE_PIE_CHART,
  SET_PIE_CHART_ERROR,
  SET_PIE_CHART_LOADING,
  SET_CHART_TYPE_PIE,
  SET_LINE_CHART,
  SET_LINE_CHART_LOADING,
  SET_LINE_LANGUAGES,
  SET_LINE_CHART_ERROR,
  SET_JOBS,
  SET_JOBS_ERROR,
  SET_JOBS_LOADING,
  SET_DATE,
  SET_SEARCH,
};
